---
deployment:
  tasks:
    - source /home/$USER/nodevenv/repositories/art-home-deploy/22/bin/activate
    - cd $CPANEL_BASE_INSTALL_PATH
    - npm install --production=false
    - npm run build
    - touch $CPANEL_BASE_INSTALL_PATH/tmp/restart.txt
